/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as HubRouteImport } from './routes/hub'
import { Route as CabDiagnosticRouteImport } from './routes/cab-diagnostic'
import { Route as AiFitTestRouteImport } from './routes/ai-fit-test'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CabDiagnosticRoute = CabDiagnosticRouteImport.update({
  id: '/cab-diagnostic',
  path: '/cab-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFitTestRoute = AiFitTestRouteImport.update({
  id: '/ai-fit-test',
  path: '/ai-fit-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai-fit-test': typeof AiFitTestRoute
  '/cab-diagnostic': typeof CabDiagnosticRoute
  '/hub': typeof HubRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai-fit-test': typeof AiFitTestRoute
  '/cab-diagnostic': typeof CabDiagnosticRoute
  '/hub': typeof HubRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai-fit-test': typeof AiFitTestRoute
  '/cab-diagnostic': typeof CabDiagnosticRoute
  '/hub': typeof HubRoute
  '/results': typeof ResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/ai-fit-test'
    | '/cab-diagnostic'
    | '/hub'
    | '/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admin'
    | '/ai-fit-test'
    | '/cab-diagnostic'
    | '/hub'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/ai-fit-test'
    | '/cab-diagnostic'
    | '/hub'
    | '/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  AiFitTestRoute: typeof AiFitTestRoute
  CabDiagnosticRoute: typeof CabDiagnosticRoute
  HubRoute: typeof HubRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cab-diagnostic': {
      id: '/cab-diagnostic'
      path: '/cab-diagnostic'
      fullPath: '/cab-diagnostic'
      preLoaderRoute: typeof CabDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-fit-test': {
      id: '/ai-fit-test'
      path: '/ai-fit-test'
      fullPath: '/ai-fit-test'
      preLoaderRoute: typeof AiFitTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  AiFitTestRoute: AiFitTestRoute,
  CabDiagnosticRoute: CabDiagnosticRoute,
  HubRoute: HubRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
